### ISSUE TITLE
mooodem has test flag on remote server [CHALBUG]

### ISSUE THREAD

**Issue by datajerk** [o-o-overflow/archiveooo#31]
Challenge URL: https://archive.ooo/c/mooodem/367/

Get test flag from remote server, does not match expected flag from web form.

Thanks.

**Comment by Jacopo** [comment]
Thanks for the report, we'll look into it.

**Comment by Jacopo** [comment]
Should be fixed, can you try again? https://archive.ooo/c/mooodem/

**Comment by datajerk** [comment]
Fixed.  Challenge returning correct flag.  Thanks.
