### ISSUE TITLE
[HINT] for back-to-qoo

### ISSUE THREAD

**Issue by cj-zoltan-balazs** [o-o-overflow/archiveooo#33]
**Challenge URL**:https://archive.ooo/c/back-to-qoo/409/
**Type**: [Write-up]
**Hint number**: 1

**Hint**:
https://cujo.com/def-con-quals-ctf-2021-the-chsh-game-entangled-qubits-and-decrypting-the-flag/

**Comment by Jacopo** [comment]
Good news, Tiffany liked at your writeup :)
I will put it in
