### ISSUE TITLE
[HINT] for qoo-or-ooo

### ISSUE THREAD

**Issue by cj-zoltan-balazs** [o-o-overflow/archiveooo#34]
**Challenge URL**: https://archive.ooo/c/qoo-or-ooo/408/
**Type**: [Write-up]
**Hint number**: 1

**Hint**:
https://cujo.com/def-con-quals-ctf-2021-the-chsh-game-entangled-qubits-and-decrypting-the-flag/

**Comment by Jacopo** [comment]
Good news -- see #33
