### ISSUE TITLE
[HINT] for smart-cryptooo

### ISSUE THREAD

**Issue by convect** [o-o-overflow/archiveooo#35]
**Challenge URL**: https://archive.ooo/c/smart-cryptooo/420/
**Type**: [Hint]
**Hint number**: 1

**Hint**: the flag is in the encrypted file (but not its original, pre-​modification, plaintext source, which is https://s3.us-west-2.amazonaws.com/archive-ooo-public2/public_files/9e0a0fc6faeac0c9a8a7b5cfde55ecb8587c30e4d8ea844a207b7b943e5edcf9/https___oooverflow.io_philosophy.html-as-it-was-at-the-time )

**Comment by Jacopo** [comment]
I originally decided not to include this as the extra notes already provide the link -- on second thought, I'll put the hint as it does give a hunch to compare the files.
