### ISSUE TITLE
[HINT] for welcome-to-dc2020-quals

### ISSUE THREAD

**Issue by MohammadAassif** [o-o-overflow/archiveooo#40]
**Challenge URL**:
**Type**: [Hint | Extra description | Extra note]
**Hint number**: 

**Hint**: OOO{this_is_the_welcome_flag}

**Comment by MohammadAassif** [comment]
There are other ways to read a file other than cat ;-) [ thanks sin9yt ]

**Comment by Jacopo** [comment]
Thanks -- that's the hint we already have though :)
